=== chai-pot/Non-Relational-DB-RIT/xml exam/XML PART 2/course.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="Courses">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Course" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Cnum" type="xsd:string" />
                            <xsd:element name="desc" type="xsd:string" />
                            <xsd:element name="section" type="xsd:string" />
                            <xsd:element name="instructor" type="xsd:string" />
                        </xsd:sequence>
                        <xsd:attribute name="num" use="optional" />
                    </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:element>
</xsd:schema>

=== chai-pot/Non-Relational-DB-RIT/xml exam/XML PART 2/course.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/css" href="course.css"?>
<Courses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="course.xsd">
    <Course num="1">
        <Cnum> ISTE 230</Cnum>
        <desc> IntroToDatabaseAndDataModeling</desc>
        <section>700(LEL)58620 </section>
        <instructor> Toni Njiric </instructor>
    </Course>
    <Course num="2">
        <Cnum> ISTE 240</Cnum>
        <desc> Web &amp;MobileII</desc>
        <section>03S1(SPL)57182 </section>
        <instructor>Jim Habermas </instructor>
    </Course>
    <Course num="3">
        <Cnum> ISTE 240 </Cnum>
        <desc> Web &amp; MobileII</desc>
        <section> 500B(SBL)58741 </section>
        <instructor>Ermir Rogova </instructor>
    </Course>
</Courses>
